Changes to travis test. Added stubs folder. Changes to travis.js.
apparatus/mu-app pull request #15
Opened 2016-09-27 13:43 UTC by eeswr

2016-09-27 15:03 UTC, mihaidma requested changes
added some comments, probably the final code will need some tunning but mostly it is ok

2016-09-27 15:03 UTC, mihaidma commented on services/travis/lib/travis.js
> +      return done(err)
return done(e)

2016-09-27 15:03 UTC, mihaidma commented on services/travis/srv/start.js
this was removed. please update like in the latest version

2016-09-27 15:03 UTC, mihaidma commented on services/travis/test/index.test.js
> +      var cachedOne = reply.cached
add also a check `t.ok(cachedOne)`

2016-09-28 09:41 UTC, mcdonnelldean commented on services/travis/lib/travis.js
> +    mu.define({role: 'store', cmd: 'get', type: 'npm'}, cmdGet)
Needs to be `tavis` for type

2016-09-28 09:41 UTC, mcdonnelldean commented on services/travis/srv/start.js
> +  mu.inbound({role: 'store', type: 'travis'}, Tcp.server({port: '6050'}))
Change port number to `6052`

2016-09-28 09:45 UTC, mcdonnelldean approved these changes

2016-09-28 09:46 UTC, mcdonnelldean approved these changes

2016-09-28 09:49 UTC, mihaidma approved these changes

2016-09-28 09:50 UTC, mcdonnelldean approved these changes

2016-09-28 09:51 UTC, mcdonnelldean approved these changes

2016-09-28 09:52 UTC, merged